name: Stable Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ISO
        run: ./build_iso.sh --stable

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(make print-version BUILD_TYPE=stable)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Stable Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          prerelease: false
          body: |
            Stable Release ${{ steps.get_version.outputs.version }}
          files: '*.iso'
